language: java
jdk:
- oraclejdk8

script:
- ./gradlew clean build test check
- sonar-scanner

cache:
  directories:
  - $HOME/.m2

addons:
  sonarcloud:
    organization: "alexsrosa-github"
    token:
      secure: 532017c5baa6f25e489f5b53afbed48ca7158155