appconfig:
  process:
    report: true
  file:
    in: data/in
    out: data/out/
    extensionpattern: dat
    includenamedone: .done.
    delimiter:
      register: รง
      items: ','
      item: '-'